### ISSUE TITLE
support ACCEPT: header, in particular Accept: application/json

### ISSUE THREAD

**Issue by gvelez17** [bluesky-social/adx#145]
it would be nice to handle Accept: header for REST clients

currently the response from an ADX server comes back as `Content-Type: application/octet-stream` so its a little hard for clients/devs to parse

REST devs probably will like to get json back when possible, or know they have to get CBOR back, but anyway negotiating the accept header will give a nice clue

```
POST /data/repo/did:key:z6MkgKCtQu1G6D4i14nCKbtvAPMt5XY2TUwdfy7wfF47VMZ9 HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/octet-stream
User-Agent: axios/0.24.0
Content-Length: 1911
Host: localhost:2583
Connection: close


:¢erootsØ*X%q c´{Á#]»ÔF6ÆcD#Ì2Ò%Ï%TmÔ?®¦gversionq c´{Á#]»ÔF6ÆcD#Ì2Ò%Ï%TmÔ?®¦¢csigX@1½*23ßn+ïýý\t@Ñ;/ENaÎ*ÜLGÉÊòôâ2C>¦¼IV«Å$¡×
drootØ*X%q ¿/º¢Teë¦¤¡AGüÈiàÔi2vülq ¿/º¢Teë¦¤¡AGüÈiàÔi2vül¦cdidx8did:key:
...

```

**Comment by dholms** [comment]
XRPC takes care of encoding 💪
