### ISSUE TITLE
Permanent Root DIDs

### ISSUE THREAD

**Issue by dholms** [bluesky-social/adx#18]
Right now the DID at the root of a user's identity is an ephemeral `did:key`, and the key related to that DID is held in either local storage or as a simple key file in the user's filesystem.

We will be introducing a more complete identity system soon. User DIDs will be rooted in a proper DID network. Starting out that will likely be the user's choice of
- Bluesky Consortium
- ION

**Comment by gribneau** [comment]
Is there any interest in extending the set of supported DIDs?

The did:psqr method supports hosting (public) identities at the same URLs as profiles, and there is a WordPress plugin to attach DID documents to WordPress author pages.

**Comment by pfrazee** [comment]
It looks similar to did:web, which we are considering since it might be nice to be able to self-host a DID like that. The trick is that you need to update your DID document, often through UI flows, and so any self-hosted mechanism that doesn't have an API for receiving writes would need a process for manually copy&pasting the doc.

**Comment by gribneau** [comment]
It is similar to did:web, but supports content negotiation so the DID document and the human-readable user profile can reside at the same URL.

The permission structure supports signed or encrypted updates using a key that has the appropriate permission, but that has not yet been added to the WordPress plugin. There is a UI for manual updates.

**Comment by dholms** [comment]
One downside of domain-based DIDs (did:web, did:psqr, did:ens, etc) is that they are not necessarily permanent. Domain names expire, and when they do your canonical identifier changes.

We use the DID as the canonical reference to the user & if it changes, every reference to that user - across all repos! - is broken. Our goal is for a user's DID to remain the same for their entire life! We know this is likely unrealistic - some users will want to switch to a different DID network - & have talked through some ways to update broken references, but this necessarily involves some friction.

Better to make the default something that is resilient & expected to last for decades without the relatively fragile renewal mechanism of DNS/ENS.

The combo of consortium + ION gives folks the option for either quick, easy, low-friction (consortium) or self-sovereign (ION). We'll consider other DIDs as they come along. But each DID added increases the resolution logic. 

DIDs are lovely in that they semantically self-describe their resolution, but you unfortunately still need the code to actually perform the resolution. The [universal resolver](https://dev.uniresolver.io/), for instance, uses a docker container for each DID method. We don't want to ship 20 docker containers just to resolve some DIDs. We'd rather have nice flows around a very small set of DIDs for the time being.

**Comment by gribneau** [comment]
> Our goal is for a user's DID to remain the same for their entire life! 

The primary use case of public square DIDs is authors publishing digitally. Author profile pages are typically long-lived. They may not last as long as the author lives, but they frequently last as long as the website. 

> But each DID added increases the resolution logic.

One of the reasons I wrote did:psqr was to simplify resolution logic.

It can be communicated thus:
```
s|did:psqr:|https://|
```
An HTTPS GET is then performed with a request header:
 ```
Accept: application/json,application/ld+json
```

Are you open to contributions?

**Comment by dholms** [comment]
> They may not last as long as the author lives, but they frequently last as long as the website.

Maybe I'm biased because of my bad habits around rapidly adopting & abandoning domains 😅 
The username in ADX provides a similar entry point for users that centers around a domain name. As you suggest, rotations of username will happen very rarely, probably about on par with the lifespan of a website - very long term for some users, medium/short term for fickle folks like me 😉 _But_ it's backed by the canonical cryptographic DID in the event of rotations. 

> Are you open to contributions?

At the moment, probably not. Though we appreciate the enthusiasm! We're building this with an initial focus on cryptographic DIDs & will be fleshing out ION + the consortium in the near term. Afterwards, we'll be going back to the drawing board to determine which additional methods may make sense to support. `did:web` is something that comes up fairly often, and we'll consider `did:psqr` as well :)

**Comment by pfrazee** [comment]
> Maybe I'm biased because of my bad habits around rapidly adopting & abandoning domains 😅

I figure, if we support a self-host-on-your-website approach, we just have to communicate "this account lives only as long as your website does."

**Comment by gribneau** [comment]
Ultimately, `did:psqr` might roll back into `did:web`. That depends on path handling and support for content negotiation, but the _also known as_ field in DID core can facilitate merging back in.

It should be possible for these two things to represent the same entity:
```
https://twitter.com/bluesky

did:foo:twitter.com/bluesky
```

The URL is human readable, and the `did` is machine readable, but they are both a form of identity referencing the same subject.

The `did:psqr` method accomplishes this with request headers, and the prototype is WordPress author profile pages. In the end, I think simplicity prevails.

**Comment by gribneau** [comment]
We've extended the WordPress plugin to handle DID updates.

The process is as simple as one might imagine - an HTTPS PUT request is made to the same address as the DID. The request body data must contain a JWS in compact serialized format to authenticate, and that JWS must be created with a key that has been granted the `admin` permission in the DID itself.

https://github.com/public-square/psqr-wordpress
