### ISSUE TITLE
Rework TID Collection SSTables

### ISSUE THREAD

**Issue by dholms** [bluesky-social/adx#88]
SSTables are currently a non-recursive data structure with relatively costly merge operations.

SSTables also have a large number of siblings, which causes quite large merkle proofs to prove the existence of some object - especially an older object in a larger table.

We should rework TID collections to use a recursive data structure, with fewer siblings, that still preserves the ability to do range queries at the structural level

**Comment by mikestaub** [comment]
Is this task pre-mature optimization? Are we sure the `TidCollection` class will live beyond the scope of this experiment?

**Comment by dholms** [comment]
Yup this is part of an ongoing discussion about the format of `TidCollection`. Collections will almost certainly live beyond the scope of this experiment, but we're actively working to figure out what shape they should have long term.

There's a chance we represent this information differently, although the interest in range queries suggests it will have a similar shape to some degree. 

The primary design goals are:
- ability to do range queries over TID
- merkle proof size for a given document
