### ISSUE TITLE
Basic schema set

### ISSUE THREAD

**Issue by dholms** [bluesky-social/adx#92]
Our current microblogging schemas are intentionally stripped down and simple. We should flesh these out and allow for more complex interactions such as replies, threading, retweets, and more.

We should release a set of schemas describing basic social media objects, including microblogs, likes, image posts and long form writing.

These schemas will be distributed on the schema network (https://github.com/bluesky-social/bluesky-experiment/issues/91)

**Comment by mikestaub** [comment]
I would not expand the interactions until the schema network is more robust.
