### ISSUE TITLE
Separate out network roles

### ISSUE THREAD

**Issue by dholms** [bluesky-social/adx#93]
Right now, a single server does all of the network roles: identity provider, DID network, personal data server, and indexer.

Each of these roles should be split out into their own entity.

**Comment by mikestaub** [comment]
This seems like a premature optimization. Do we know what all the network roles are at this stage?

**Comment by whyrusleeping** [comment]
I think the point is mostly that these roles should be *conceptually* separate. Bundling them together could cause us to build a protocol that is less flexible than it should be.
